import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Button,
  Container,
  FormControl,
  FormHelperText,
  FormLabel,
  Input,
  Text,
} from "@chakra-ui/react";
import FormOne from "../components/FormOne/FormOne";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ backgroundColor: "#171717", minHeight: "100vh" }}>
        <Container maxW={"90%"} p={5} color={"#FFFFFF"}>
          <Text textAlign={"center"}>Form</Text>
          <FormOne />
        </Container>
      </main>
    </>
  );
}
